### ISSUE TITLE
Issue with POST localGateway/realizarPago

### ISSUE THREAD

**Issue by jperez8** [creagia/laravel-redsys#29]
Hi, i'm trying to make a payment with redirect method. When i try to accept a payment `http://localhost/redsys/localGateway/post
` is returning a 500.

I'm using Sail.

I have these variables on my .env
<img width="351" alt="Screenshot 2023-10-03 at 01 27 20" src="https://github.com/creagia/laravel-redsys/assets/48395571/5eb304ba-f8e1-4b74-ad25-ac4d6bf1754a">

<img width="1235" alt="Screenshot 2023-10-03 at 01 31 13" src="https://github.com/creagia/laravel-redsys/assets/48395571/14d25de1-e45c-413c-b88f-65979cae6b3c">

This is the error I'm getting
<img width="1702" alt="Screenshot 2023-10-03 at 01 27 50" src="https://github.com/creagia/laravel-redsys/assets/48395571/89058ae6-926a-47fb-bef4-5a614eeb0d9a">

Thanks in advance, it is a pretty cool package!
Best Regards

**Comment by dtorras** [comment]
I was able to reproduce it using Laravel Sail. 

I'm afraid this is a Laravel Sail bug when marking HTTP requests to the same server. It works when using any other web server. Here you have some bug reports on laravel/sail:

https://github.com/laravel/sail/issues/103
https://github.com/laravel/sail/issues/115

**Comment by jperez8** [comment]
Thanks, I've been able to test it setting `REDSYS_ENVIRONMENT=test`
