### ISSUE TITLE
Error Code SIS0463

### ISSUE THREAD

**Issue by jperez8** [creagia/laravel-redsys#41]
Hi, I'm trying to make a payment with a token previously generated but the request is being denied, period.

This is the log generated: 
`{"Ds_Date": "25/01/2024", "Ds_Hour": "18:31", "Ds_Order": "240100000204", "Ds_Amount": "31675", "Ds_Currency": "978", "Ds_Response": "0118", "Ds_Terminal": "001", "Ds_ErrorCode": "SIS0463", "Ds_Card_Country": "724", "Ds_MerchantCode": "336099247", "Ds_MerchantData": "", "Ds_SecurePayment": "0", "Ds_TransactionType": "0", "Ds_ConsumerLanguage": "1", "Ds_AuthorisationCode": "      "}`

Here how i'm creating the token:
<img width="583" alt="image" src="https://github.com/creagia/laravel-redsys/assets/48395571/042b9431-8c81-4a98-9b11-38d8cd8510aa">

    
Here how i'm making second payment:
<img width="565" alt="image" src="https://github.com/creagia/laravel-redsys/assets/48395571/e2d88e58-0e97-4d14-9457-47df44778656">

    
I did some research and SIS0463 means 'Metodo de pago no permitido', any idea how to solve this?

**Comment by dtorras** [comment]
What Redsys environment are you using with this result? test or production?

**Comment by jperez8** [comment]
test

**Comment by jperez8** [comment]
Hi, do you have any new info about this? @dtorras

**Comment by dtorras** [comment]
Can you share what test card are you using to test it? 
After adding the `DS_MERCHANT_EXCEP_SCA` param, I was able to save a card token and create a recurring payment with this card data in the test environment. 

```diff
$response = RequestBuilder::newRequest(new RequestParameters(
    amountInCents: $subscription->getTotalAmount(),
    currency: Currency::EUR,
    transactionType: TransactionType::Autorizacion,
+    excepSca: 'MIT',
))->associateWithModel($subscription)
    ->usingCard(
        CofType::Recurring,
        $redsysCard
    )->post();
```

```
Número de tarjeta: 4548812049400004
Caducidad: 12/23
Código CVV2: 123
```

**Comment by dtorras** [comment]
@jperez8 I'm closing this issue for now. Feel free to reopen it if you have more details.
