### ISSUE TITLE
Error order_number ¿Limite de tamaño?

### ISSUE THREAD

**Issue by coriaweb** [creagia/laravel-redsys#68]
Este campo order_number, "creo" que tiene un limite de 20, lo he visto en la tabla y lo he cambiado a tipo text, pero aun asi.. creo que tiene algo por dentro, no me deja poner algo personalizado.

Si queremos poner algo personalizado, como en mi caso esto:

// Generar un número de pedido único
$orderNumber = 'Autorizacion-' . now()->format('YmdHis') . '-' . $user->id;

No se registrará la tarjeta en la base de datos, ¿Donde mas puede tener el limite este? Seria util quitar el limite este a nivel general o sólo es útil para mi?

Saludos!

**Comment by dtorras** [comment]
@coriaweb la idea de este paquete es simplificar la implementación de Redsys en una aplicación Laravel. El número de pedido tiene que ser un número único y, para simplificar esto, he optado por limitar a que sea un número autoincremental que se genera automáticamente.

Si necesitas personalizar más el uso de Redsys, te recomiendo que uses [redsys-php](https://github.com/creagia/redsys-php), que es la base de este proyecto y te permitirá más flexibilidad para implementar la solución a tu gusto.
