### ISSUE TITLE
Error en la redirección

### ISSUE THREAD

**Issue by Alicia-ls** [creagia/laravel-redsys#7]
Buenas, he ido siguiendo todos los pasos de la documentación, y me aparece este error.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `redsys_payments` (`product_description`, `amount`, `currency`, `language`, `model_id`, `model_type`, `order_number`, `uuid`, `updated_at`, `created_at`) values (Product description, 10, 978, 0, ?, App\Models\Payment, 2205000001, fdf13158-618c-4498-8c1e-f100a8b90cbf, 2022-05-12 08:04:47, 2022-05-12 08:04:47))

**Comment by dtorras** [comment]
Have you managed to solve the issue? Since you closed it, I guess it was related to your code?

**Comment by Alicia-ls** [comment]
> Have you managed to solve the issue? Since you closed it, I guess it was related to your code?

No, I have used finally the other library php redsys creagia, because I couldn´t find the way to solve the other problem. 

Thanks anyway.
