### ISSUE TITLE
Issue with POST localGateway/realizarPago

### ISSUE THREAD

**Issue by annajuni** [creagia/laravel-redsys#8]
Hi! I'm trying to use your package, but it seems that the methods of the local gateway are not working, 
how can I make the payment response as the payment is made?

Thanks!!

Regards

**Comment by dtorras** [comment]
@annajuni can you provide any more detail? To test your payments locally, you should define your Redsys environment to `local` on your `.env`:

```
REDSYS_ENVIRONMENT=local
```

**Comment by annajuni** [comment]
Hi @dtorras thanks for your answer. Si quieres hablamos en español, como quieras!
si que tengo puesta la variable de entorno local, me redirige al local gateway pero allí se me queda colgado cuando quiere hacer la petición POST, se me queda todo el backend bloqueado y tengo que reiniciarlo.

**Comment by dtorras** [comment]
I guess your application is blocked trying to send the `POST` response notification. Sending `POST` requests to local domains is difficult sometimes.

In the below example, the gateway will make a POST request to `https://laravel-redsys-example.test/redsys/notification` (this route is generated and managed by the package).

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/240932/172893777-f5abbc08-1192-4629-837e-9a5e6435bc79.png">

Can you confirm that your `DS_MERCHANT_MERCHANTURL` is correct? Can you attach a similar screenshot from your environment if it looks fine?

Thanks.

**Comment by jperez8** [comment]
Hi, I'm getting same error.
It seems merchant url is okay.

<img width="1455" alt="Screenshot 2023-10-03 at 01 13 27" src="https://github.com/creagia/laravel-redsys/assets/48395571/12fcaa77-4f9b-4494-9946-eaffd9111345">
